name: Docker Deploy CI
# Trigger the workflow on release activity
on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [published, created, edited]
    branches:    
      # Push events on main branch
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Build the Docker image
       run: echo "build"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
     - name: Test via Junit 
       run: echo "test"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
     - name: Deploys the Docker image
       run: echo "deploy"
